networks:
    db:
        driver: bridge

services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb_container
        restart: always
        environment:
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=hackr
            - MYSQL_USER=root
            - MYSQL_PASSWORD=
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - db
    app:
        build:
            context: .
            dockerfile: dockerfile
        container_name: api_container
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mariadb
        networks:
            - db
        env_file:
            - .env

    nginx:
        image: nginx:latest
        container_name: nginx_container
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - db


volumes:
    mariadb_data:
